on: [push]
jobs:
  build_latex:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: xu-cheng/texlive-action@v2
        with:
          docker_image: xucheng/texlive-full:latest
          run: |
            apk add make
            make force

      - name: List output files
        run: ls -l out/

      - name: Upload SVG files as Artifacts
        uses: actions/upload-artifact@v2
        with:
          name: svg-files
          path: out/*.svg

      - name: Deploy to GitHub Pages
        run: |
          git config --global user.name 'GitHub Actions'
          git config --global user.email 'actions@github.com'
          git checkout -b gh-pages
          find out -name "*.svg" -exec mv {} ./ \;
          git add .
          git commit -m "Deploy SVGs"
          git push --force origin gh-pages
