name: Build and Deploy LaTeX Documents

on:
  push:
    branches:
      - main

jobs:
  build_latex:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up LaTeX environment
        uses: xu-cheng/texlive-action@v2
        with:
          docker_image: xucheng/texlive-full:latest
          run: |
            apk add make
            make force

      - name: List output files
        run: ls -l out/

      - name: Upload SVG files as Artifacts
        uses: actions/upload-artifact@v2
        with:
          name: svg-files
          path: out/*.svg

      - name: Set up Git
        run: |
          git config user.name 'GitHub Actions'
          git config user.email 'actions@github.com'

      - name: Check out gh-pages branch
        run: |
          git fetch
          git checkout gh-pages || git checkout --orphan gh-pages

      - name: Copy SVG files to root
        run: |
          mkdir -p svg
          cp out/*.svg svg/

      - name: Commit and push changes
        run: |
          git add svg/
          git status
          git commit -m "Deploy updated SVGs" --allow-empty
          git push --force origin gh-pages
